stages:
  data_ingestion:
    cmd: python3 src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    outs:
    - data/raw
  data_preprocessing:
    cmd: python3 src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/processed
  feature_engineering:
    cmd: python3 src/features/feature_engineering.py
    deps:
    - data/processed
    - src/features/feature_engineering.py
    outs:
    - data/features

  model_building:
    cmd: python3 src/model/model_building.py
    deps:
    - data/features
    - src/model/model_building.py
    outs:
    - models
  model_evaluation:
    cmd: python3 src/model/model_evaluation.py
    deps:
    - models
    - src/model/model_evaluation.py
    metrics:
    - evaluation/metrics.yaml:
        cache: false